import type { CasePayload, CaseSnapshot } from "../shared/nidarshan";

export const DEMO_CASE_NUMBER = "KRN-261014-001";

export function createDemoPayload(): CasePayload {
  return {
    summary: {
      files: 4,
      entities: 34,
      links: 52,
      critical: 3,
      high: 5,
      totalAmount: 824500,
      analysisDuration: "00:01:42",
    },
    sourceFiles: [
      { name: "sample_upi.csv", type: "UPI ledger", rows: 15, hash: "a7b4…91d2", status: "verified" },
      { name: "sample_cdr.csv", type: "Call detail record", rows: 20, hash: "93c1…48fe", status: "verified" },
      { name: "sample_ipdr.csv", type: "IP session log", rows: 10, hash: "e20f…7ac1", status: "verified" },
      { name: "sample_chat.txt", type: "Chat export", rows: 18, hash: "d4a9…c001", status: "verified" },
    ],
    entities: [
      {
        id: "victim-upi",
        value: "ravi.sharma@okaxis",
        type: "VICTIM",
        risk: 22,
        tier: "LOW",
        summary: "Origin account in the complaint narrative",
        reasons: ["Account appears as the source of the reported ₹50,000 transfer"],
        sourceCount: 2,
        firstSeen: "12 Oct 2026 · 13:58",
        lastSeen: "12 Oct 2026 · 14:03",
        tags: ["complainant", "origin"],
      },
      {
        id: "mule-01",
        value: "9876543210@paytm",
        type: "MULE",
        risk: 92,
        tier: "CRITICAL",
        summary: "Primary receiving account with rapid downstream forwarding",
        reasons: [
          "Received ₹50,000 from the victim and split it across 3 accounts within 8 minutes",
          "Account received funds from 5 unique senders in the same 24-hour window",
          "UPI handle appears in mule-recruitment chat evidence",
          "Phone number is linked to IMEI 356938035643809 and a reused IP address",
        ],
        sourceCount: 4,
        firstSeen: "12 Oct 2026 · 13:59",
        lastSeen: "12 Oct 2026 · 14:21",
        tags: ["rapid-forwarding", "mule-candidate", "shared-device"],
      },
      {
        id: "mule-02",
        value: "aarti.k@oksbi",
        type: "MULE",
        risk: 84,
        tier: "CRITICAL",
        summary: "Second-hop account that received split proceeds",
        reasons: [
          "Received ₹18,000 four minutes after the victim transfer",
          "Same IP address observed in IPDR sessions for two other phone numbers",
          "Funds were withdrawn as a round-number cash-out within 9 minutes",
        ],
        sourceCount: 3,
        firstSeen: "12 Oct 2026 · 14:07",
        lastSeen: "12 Oct 2026 · 14:16",
        tags: ["second-hop", "cash-out"],
      },
      {
        id: "cashout",
        value: "cashout.rahul@ibl",
        type: "CASHOUT",
        risk: 78,
        tier: "CRITICAL",
        summary: "Final destination for a rapid withdrawal sequence",
        reasons: [
          "Received ₹12,000 from a linked mule account inside the 10-minute burst",
          "Account is associated with a device seen in the CDR and IPDR sources",
          "Round-number withdrawal pattern is consistent with cash-out behavior",
        ],
        sourceCount: 3,
        firstSeen: "12 Oct 2026 · 14:12",
        lastSeen: "12 Oct 2026 · 14:21",
        tags: ["cash-out", "round-number"],
      },
      {
        id: "account-4498",
        value: "Account •••• 4498",
        type: "ACCOUNT",
        risk: 86,
        tier: "CRITICAL",
        summary: "Settlement account receiving multiple sources",
        reasons: [
          "Received funds from 5 unique sender accounts",
          "Two linked accounts forwarded funds within 5 minutes of receipt",
        ],
        sourceCount: 3,
        firstSeen: "12 Oct 2026 · 14:03",
        lastSeen: "12 Oct 2026 · 14:18",
        tags: ["aggregator", "rapid-forwarding"],
      },
      {
        id: "device-imei",
        value: "IMEI 356938035643809",
        type: "DEVICE",
        risk: 71,
        tier: "HIGH",
        summary: "Handset reused across three SIM identities",
        reasons: [
          "IMEI linked to 3 phone numbers within a 48-hour window",
          "Device appears in CDR and IPDR data sources",
        ],
        sourceCount: 2,
        firstSeen: "11 Oct 2026 · 17:44",
        lastSeen: "12 Oct 2026 · 14:21",
        tags: ["sim-swap", "cross-source"],
      },
      {
        id: "ip-reused",
        value: "103.21.244.17",
        type: "IP_ADDRESS",
        risk: 64,
        tier: "HIGH",
        summary: "Shared IP observed across two devices and three accounts",
        reasons: [
          "IP address appears in both CDR enrichment and IPDR session data",
          "Three accounts were active from this address within 17 minutes",
        ],
        sourceCount: 2,
        firstSeen: "12 Oct 2026 · 14:02",
        lastSeen: "12 Oct 2026 · 14:19",
        tags: ["cross-source", "reused-ip"],
      },
      {
        id: "phone-1",
        value: "+91 98765 43210",
        type: "PHONE",
        risk: 59,
        tier: "HIGH",
        summary: "Subscriber linked to the primary mule account",
        reasons: ["Phone number is associated with the shared IMEI and mule UPI handle"],
        sourceCount: 2,
        firstSeen: "12 Oct 2026 · 13:56",
        lastSeen: "12 Oct 2026 · 14:21",
        tags: ["mule-contact"],
      },
      {
        id: "phone-2",
        value: "+91 98204 77108",
        type: "PHONE",
        risk: 48,
        tier: "MEDIUM",
        summary: "Secondary subscriber using the same device",
        reasons: ["Same IMEI observed with a second phone number in CDR records"],
        sourceCount: 1,
        firstSeen: "11 Oct 2026 · 17:44",
        lastSeen: "11 Oct 2026 · 18:02",
        tags: ["sim-swap"],
      },
      {
        id: "chat-actor",
        value: "Chat contact •••• 3210",
        type: "PHONE",
        risk: 55,
        tier: "HIGH",
        summary: "Contact appears in recruitment and OTP request messages",
        reasons: ["Chat export contains account-rental, OTP, and transfer instructions"],
        sourceCount: 1,
        firstSeen: "12 Oct 2026 · 13:41",
        lastSeen: "12 Oct 2026 · 14:06",
        tags: ["chat-intel", "otp-request"],
      },
    ],
    nodes: [
      { id: "victim-upi", label: "Ravi Sharma", type: "VICTIM", risk: 22, tier: "LOW", x: 105, y: 285, subtitle: "ravi.sharma@okaxis" },
      { id: "mule-01", label: "Mule 01", type: "MULE", risk: 92, tier: "CRITICAL", x: 335, y: 195, subtitle: "9876543210@paytm" },
      { id: "mule-02", label: "Mule 02", type: "MULE", risk: 84, tier: "CRITICAL", x: 570, y: 125, subtitle: "aarti.k@oksbi" },
      { id: "account-4498", label: "Settlement", type: "ACCOUNT", risk: 86, tier: "CRITICAL", x: 570, y: 295, subtitle: "Account •••• 4498" },
      { id: "cashout", label: "Cash-out", type: "CASHOUT", risk: 78, tier: "CRITICAL", x: 805, y: 210, subtitle: "cashout.rahul@ibl" },
      { id: "device-imei", label: "Shared device", type: "DEVICE", risk: 71, tier: "HIGH", x: 340, y: 410, subtitle: "IMEI 356938035643809" },
      { id: "ip-reused", label: "Reused IP", type: "IP_ADDRESS", risk: 64, tier: "HIGH", x: 580, y: 455, subtitle: "103.21.244.17" },
      { id: "phone-1", label: "Phone 01", type: "PHONE", risk: 59, tier: "HIGH", x: 100, y: 455, subtitle: "+91 98765 43210" },
    ],
    edges: [
      { id: "e1", from: "victim-upi", to: "mule-01", label: "₹50,000 · 14:03", amount: 50000, timestamp: "12 Oct 2026 · 14:03", risk: "red", evidenceId: "ev-upi-1" },
      { id: "e2", from: "mule-01", to: "mule-02", label: "₹18,000 · 14:07", amount: 18000, timestamp: "12 Oct 2026 · 14:07", risk: "orange", evidenceId: "ev-upi-2" },
      { id: "e3", from: "mule-01", to: "account-4498", label: "₹20,000 · 14:09", amount: 20000, timestamp: "12 Oct 2026 · 14:09", risk: "orange", evidenceId: "ev-upi-3" },
      { id: "e4", from: "mule-01", to: "cashout", label: "₹12,000 · 14:12", amount: 12000, timestamp: "12 Oct 2026 · 14:12", risk: "red", evidenceId: "ev-upi-4" },
      { id: "e5", from: "mule-02", to: "cashout", label: "₹8,000 · 14:16", amount: 8000, timestamp: "12 Oct 2026 · 14:16", risk: "orange", evidenceId: "ev-upi-5" },
      { id: "e6", from: "account-4498", to: "cashout", label: "₹10,000 · 14:18", amount: 10000, timestamp: "12 Oct 2026 · 14:18", risk: "red", evidenceId: "ev-upi-6" },
      { id: "e7", from: "phone-1", to: "device-imei", label: "uses", timestamp: "12 Oct 2026 · 13:56", risk: "purple", evidenceId: "ev-cdr-1" },
      { id: "e8", from: "device-imei", to: "mule-01", label: "linked to", timestamp: "12 Oct 2026 · 14:02", risk: "purple", evidenceId: "ev-cdr-2" },
      { id: "e9", from: "device-imei", to: "ip-reused", label: "session", timestamp: "12 Oct 2026 · 14:05", risk: "blue", evidenceId: "ev-ipdr-1" },
      { id: "e10", from: "ip-reused", to: "account-4498", label: "observed", timestamp: "12 Oct 2026 · 14:11", risk: "blue", evidenceId: "ev-ipdr-2" },
    ],
    timeline: [
      { id: "t1", timestamp: "2026-10-12T13:41:00+05:30", timeLabel: "13:41", title: "Mule recruitment signal detected", detail: "“bhai tera account 2 din ke liye chahiye, 30% commission milega”", tag: "CHAT", tone: "orange", relatedEntity: "chat-actor" },
      { id: "t2", timestamp: "2026-10-12T13:58:00+05:30", timeLabel: "13:58", title: "Victim account active", detail: "Ravi Sharma’s UPI handle appears in the evidence window", tag: "UPI", tone: "blue", relatedEntity: "victim-upi" },
      { id: "t3", timestamp: "2026-10-12T14:03:00+05:30", timeLabel: "14:03", title: "Reported transfer received", detail: "₹50,000 moved into 9876543210@paytm", tag: "₹50,000", tone: "red", relatedEntity: "mule-01" },
      { id: "t4", timestamp: "2026-10-12T14:07:00+05:30", timeLabel: "14:07", title: "Rapid split initiated", detail: "₹18,000 forwarded to aarti.k@oksbi four minutes after receipt", tag: "BURST", tone: "orange", relatedEntity: "mule-02" },
      { id: "t5", timestamp: "2026-10-12T14:12:00+05:30", timeLabel: "14:12", title: "Cash-out path identified", detail: "₹12,000 routed to cashout.rahul@ibl", tag: "CASH-OUT", tone: "red", relatedEntity: "cashout" },
      { id: "t6", timestamp: "2026-10-12T14:19:00+05:30", timeLabel: "14:19", title: "Shared IP confirmed", detail: "103.21.244.17 reused across three account sessions", tag: "IPDR", tone: "purple", relatedEntity: "ip-reused" },
      { id: "t7", timestamp: "2026-10-12T14:21:00+05:30", timeLabel: "14:21", title: "SIM-swap pattern linked", detail: "One IMEI associated with three phone numbers within 48 hours", tag: "CDR", tone: "yellow", relatedEntity: "device-imei" },
    ],
    evidence: [
      { id: "ev-upi-1", source: "UPI", title: "Victim transfer", detail: "₹50,000 · ravi.sharma@okaxis → 9876543210@paytm", timestamp: "12 Oct 2026 · 14:03", confidence: 99, accent: "red" },
      { id: "ev-upi-2", source: "UPI", title: "Rapid forwarding", detail: "₹18,000 · 9876543210@paytm → aarti.k@oksbi", timestamp: "12 Oct 2026 · 14:07", confidence: 99, accent: "orange" },
      { id: "ev-cdr-2", source: "CDR", title: "Shared IMEI link", detail: "IMEI 356938035643809 associated with +91 98765 43210", timestamp: "12 Oct 2026 · 14:02", confidence: 94, accent: "purple" },
      { id: "ev-ipdr-2", source: "IPDR", title: "Cross-source IP link", detail: "103.21.244.17 observed in 3 account sessions", timestamp: "12 Oct 2026 · 14:19", confidence: 89, accent: "blue" },
      { id: "ev-chat-1", source: "CHAT", title: "Recruitment message", detail: "Account rental offer with 30% commission promise", timestamp: "12 Oct 2026 · 13:41", confidence: 91, accent: "orange" },
    ],
    alerts: [
      { title: "Rapid fund splitting", detail: "₹50,000 split across three accounts within eight minutes", severity: "CRITICAL", timestamp: "14:07" },
      { title: "Shared device / SIM-swap", detail: "Three phone identities mapped to IMEI 356938035643809", severity: "HIGH", timestamp: "14:21" },
      { title: "Cross-source IP reuse", detail: "Same IP appears in CDR enrichment and IPDR sessions", severity: "HIGH", timestamp: "14:19" },
    ],
    recommendations: [
      "Prioritize human review of 9876543210@paytm and its linked settlement accounts.",
      "Preserve original CDR, IPDR, UPI, and chat exports with their SHA-256 hashes.",
      "Request transaction-level confirmation for the 14:03–14:21 burst window.",
      "Consider device examination for IMEI 356938035643809 subject to applicable authorization.",
    ],
    generatedAt: "14 Oct 2026 · 09:42 IST",
  };
}

export function createDemoCase(id = 1): CaseSnapshot {
  return {
    id,
    caseNumber: DEMO_CASE_NUMBER,
    name: "UPI mule network · Pune",
    status: "active",
    createdAt: "2026-10-14T04:12:00.000Z",
    updatedAt: "2026-10-14T04:42:00.000Z",
    payload: createDemoPayload(),
  };
}
