import PDFDocument from "pdfkit";
import { buildIntelligence } from "./intelligence";
import type { EvidenceFile } from "../drizzle/schema";

export function buildReportData(caseNumber: string, files: EvidenceFile[], apkCount = 0) {
  const intelligence = buildIntelligence(files);
  const critical = intelligence.entities.filter(entity => entity.tier === "CRITICAL");
  return {
    caseNumber,
    generatedAt: new Date().toISOString(),
    summary: {
      files: files.length,
      entities: intelligence.entityCount,
      links: intelligence.linkCount,
      apkArtifacts: apkCount,
      critical: critical.length,
      analysisDuration: `${Math.max(1, files.length * 2)} seconds (server-side analysis)`,
    },
    primeSuspects: intelligence.entities.slice(0, 5),
    timeline: intelligence.timeline.slice(0, 10),
    recommendations: critical.length ? critical.map(entity => `Priority human review: ${entity.value} (${entity.tier}, ${entity.score}/100)`) : ["Review extracted entities against original source records before action."],
    integrity: files.map(file => ({ file: file.originalName, sha256: file.sha256 })),
    disclaimer: "For investigative assistance only. Findings require human verification and applicable authorization.",
  };
}

export async function generatePdfReport(report: ReturnType<typeof buildReportData>) {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ size: "A4", margin: 42 });
    doc.on("data", chunk => chunks.push(Buffer.from(chunk)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(18).font("Helvetica-Bold").text("NIDARSHAN INVESTIGATIVE BRIEF");
    doc.moveDown(0.3).fontSize(9).font("Helvetica").fillColor("#555555").text(`Case ${report.caseNumber} · Generated ${report.generatedAt}`);
    doc.moveDown().fillColor("#111111").fontSize(11).font("Helvetica-Bold").text("Case summary");
    doc.fontSize(9).font("Helvetica").text(`${report.summary.files} files · ${report.summary.entities} entities · ${report.summary.links} links · ${report.summary.apkArtifacts} APK artifacts · ${report.summary.critical} critical entities`);

    doc.moveDown().fontSize(11).font("Helvetica-Bold").text("Prime suspects");
    report.primeSuspects.forEach((entity, index) => {
      doc.fontSize(9).font("Helvetica").text(`${index + 1}. ${entity.value} · ${entity.type} · ${entity.score}/100 · ${entity.tier}`);
      doc.fontSize(8).fillColor("#555555").text(`   ${entity.reasons[0] ?? "Source-linked entity"}`).fillColor("#111111");
    });

    doc.moveDown().fontSize(11).font("Helvetica-Bold").text("Evidence timeline");
    report.timeline.forEach(item => doc.fontSize(8.5).font("Helvetica").text(`${new Date(item.timestamp).toISOString()} · ${item.file} · ${item.summary}`));

    doc.moveDown().fontSize(11).font("Helvetica-Bold").text("Integrity and recommendations");
    report.integrity.forEach(item => doc.fontSize(8).font("Helvetica").text(`${item.file} · SHA-256 ${item.sha256}`));
    report.recommendations.forEach(item => doc.fontSize(8.5).text(`• ${item}`));
    doc.moveDown().fontSize(7).fillColor("#666666").text(`${report.disclaimer} Generated by NIDARSHAN.`);
    doc.end();
  });
}
